export  const CHANGE_SERVER_URL='CHANGE_SERVER_URL';
export const CHANGE_MARKETDATA_URL='CHANGE_MARKETDATA_URL';
export const PARTICIPATION_ALERT='PARTICIPATION_ALERT';
export const GET_TOKEN='GET_TOKEN';
